# test execution
# flexget --test execute
schedules:
  - tasks: '*'
    interval:
      minutes: 5
tasks:
  Anime:
    rss: https://subsplease.org/rss/?t&r=1080
    series:
      - Lycoris Recoil
      - Mamahaha no Tsurego ga Motokano datta
      - Overlord
      - Yofukashi no Uta
      - Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e S2
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
