# test execution
# flexget --test execute
schedules:
  - tasks: '*'
    interval:
      minutes: 5
tasks:
  Anime:
    rss: https://subsplease.org/rss/?t&r=1080
    series:
      - Akiba Maid Sensou
      - Blue Lock
      - Chainsaw Man
      - Kage no Jitsuryokusha ni Naritakute!
      - Mob Psycho 100 S3
      - Spy x Family
      - Urusei Yatsura
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
