# Check configuration syntax
# flexget check
#
# Test execution
# flexget --test execute
schedules:
  - tasks: '*'
    interval:
      minutes: 5
tasks:
  subsplease:
    rss: https://subsplease.org/rss/?t&r=1080
    series:
      - Dark Gathering
      - Helck
      - Horimiya - Piece
      - Jujutsu Kaisen
      - Masamune-kun no Revenge S2
      - Mushoku Tensei S2
      - Nanatsu no Maken ga Shihai suru
      - Ryza no Atelier
      - Undead Girl Murder Farce
      - Zom 100 - Zombie ni Naru made ni Shitai 100 no Koto
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
  erai-raws:
    rss: https://nyaa.si/?page=rss&q=1080p&c=0_0&f=0&u=Erai-raws
    series:
      - Watashi no Shiawase na Kekkon
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
