# Check configuration syntax
# flexget check
#
# Test execution
# flexget --test execute
schedules:
  - tasks: '*'
    interval:
      minutes: 5
tasks:
  Anime:
    rss: https://subsplease.org/rss/?t&r=1080
    series:
      - Birdie Wing - Golf Girls' Story
      - Jigokuraku
      - Kimetsu no Yaiba - Katanakaji no Sato-hen
      - Kono Subarashii Sekai ni Bakuen wo!
      - Kubo-san wa Mob wo Yurusanai
      - Mahoutsukai no Yome S2
      - Mashle
      - Mobile Suit Gundam - The Witch from Mercury
      - Oshi no Ko
      - Ousama Ranking - Yuuki no Takarabako
      - Vinland Saga S2
      - Yamada-kun to Lv999 no Koi wo Suru
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
