# Check configuration syntax
# flexget check
#
# Test execution
# flexget --test execute
schedules:
  - tasks: "*"
    interval:
      minutes: 5
tasks:
  subsplease:
    rss: https://subsplease.org/rss/?t&r=1080
    series:
      - Dark Gathering
      - Goblin Slayer S2
      - Helck
      - Hyakkano
      - Jujutsu Kaisen
      - Kage no Jitsuryokusha ni Naritakute! S2
      - Kikansha no Mahou wa Tokubetsu desu
      - Kusuriya no Hitorigoto
      - Shangri-La Frontier
      - Sousou no Frieren
      - Spy x Family
      - Tearmoon Teikoku Monogatari
      - Uma Musume - Pretty Derby S3
      - Under Ninja
      - Watashi no Oshi wa Akuyaku Reijou
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
  ember:
    rss: https://nyaa.si/?page=rss&q=1080p+ember&c=0_0&f=0&u=Ember_Encodes
    series:
      - Undead Unluck
    transmission:
      host: localhost
      port: 9091
      username: transmission
      password: transmission
