#!/bin/sh
# autostart
flexget daemon start -d &

# microphone
sleep 3 &&
	noisetorch -i alsa_input.pci-0000_2f_00.4.analog-stereo &&
	pactl set-source-volume alsa_input.pci-0000_2f_00.4.analog-stereo 45% &&
	pactl set-source-volume 'NoiseTorch Microphone' 140% &

# mouse
xinput --set-prop 15 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 15 'libinput Accel Speed' -0.4

# display
xrandr --output DP-4 --left-of DP-2 &
# Display Power Management Signaling
xset s off -dpms
