#!/bin/sh
# shorten commands
alias cal='cal -m'
alias m='neomutt'
alias n='newsboat'
alias shck="shellcheck"
alias t='watch -n 0.1 transmission-remote -l'
alias tsm='transmission-remote'
alias tsml='transmission-remote -l'
alias v='nvim'
alias z='zathura'
alias zzz="systemctl suspend"

# change directories
alias cdd="cd ~/Data; ls"
alias cdm="cd ~/Data/Education/master; ls"
alias cdmc="cd ~/Data/Education/master/2022S; ls"
alias cdt="cd ~/Temp; ls"
alias cdtorr="cd ~/Temp/Torrents; ls"

# open files
alias risedb="zathura ~/Data/Games/MHRise/MHRise_DB.pdf"

# go up
alias .1="cd .."
alias .2="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."

# colorize commands
alias diff="diff --color=auto"
alias ip="ip -color=auto"
alias grep="grep --color=auto"
alias ls="ls -lAh --color=auto"

# XDG Base Directory Specification
alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc"
