#!/bin/sh

# autostart apps
dunst &
flameshot & 
redshift &
udiskie &
transmission-daemon &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &

# device specific
case "$(cat /proc/sys/kernel/hostname)" in
	*"desktop"*)
		# Desktop specific
		flexget daemon start -d &
		noisetorch -i alsa_input.pci-0000_0a_00.4.analog-stereo &
		pactl set-source-volume alsa_input.pci-0000_0a_00.4.analog-stereo 45% &
		xrandr --output DisplayPort-3 --left-of DisplayPort-1 &
		;;
	*"laptop"*)
		# Laptop specific
                blueman-applet &
                nm-applet &
		;;
	esac

# X11 specific
xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"
xrandr --dpi 96

# Display Power Management Signaling
xset s off -dpms

# keyboard settings
xset r 66 # caps lock

# mouse settings
xinput --set-prop 8 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 8 'libinput Accel Speed' -0.4

# start window manager
exec qtile start
