PPU-5446a2645880eefa75f7e374abd6b7818511e2ef:
  Unlock FPS:
    Demon's Souls:
      BLES00932:
        01.00: true
  Disable Motion Blur:
    Demon's Souls:
      BLES00932:
        01.00: true
  Skip Intro Videos:
    Demon's Souls:
      BLES00932:
        01.00: true