#!/bin/sh
# Aliases for often used commands.

# man zshbuiltins
alias -g C='| wl-copy'
alias -g P='"$(wl-paste)"'
alias -s git='git clone'
alias -s jpg=imv
alias -s mkv=mpv
alias -s mp4=mpv
alias -s ods=localc
alias -s pdf='$READER'
alias -s png=imv
alias -s webm=mpv
alias -s xopp=xournalpp

# Color automatically
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

# Often used directories
alias cadv='cd $PROGRAMMINGDIR/advent-of-code-2022'
alias cda='cd "$DATADIR"; l'
alias cdf='cd "$DOTDIR"; l'
alias cf='cd "$MASTERDIR/projektarbeit2/fermions"; l'
alias cm='cd "$MASTERDIR"; l'
alias cmc='cd "$MASTERDIR/2023s"; l'
alias cn='cd "$DATADIR/notes"; l'
alias cpr='cd "$PROGRAMMINGDIR"; l'
alias cpro='cd "$MASTERDIR/projektarbeit2/projectwork"; l'
alias ct='cd "$TEMPDIR"; l'
alias ctor='cd "$TORRENTDIR"; l'
alias vdf='cd "$DOTDIR"; $EDITOR'

# fd
alias fd='fd --follow --hidden'
alias fd1='fd --exact-depth 1'
alias ftree='fd | tree --fromfile'

# Git
alias g='git'
alias grt='cd "$(git rev-parse --show-toplevel)"'
alias gs='' # Don't run Ghostscript by mistake.

# Go up directories
alias .1='cd ../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'

# Interactive and verbose
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'

# lsd
alias l='lsd --long --almost-all'
alias lt='lsd --tree --almost-all'

# Neovim
alias sv='sudoedit'
alias v='$EDITOR'

# Pacman
alias aurs='paru -Slq | fzf --preview "paru -Si {}" | xargs -ro paru -S'
alias explicit-installed='pacman -Qqen | grep -vx "$(pacman -Qqg texlive)"'
alias mirror='sudo reflector --verbose --latest 8 --sort rate --protocol https --save /etc/pacman.d/mirrorlist'
alias pacq='pacman -Qq | fzf --preview "pacman -Qi {}" | xargs -ro pacman -Qi'
alias pacr='pacman -Qqe | fzf --preview "pacman -Qi {}" | xargs -ro sudo pacman -Rns'
alias pacs='pacman -Slq | fzf --preview "pacman -Si {}" | xargs -ro sudo pacman -S'
alias pacsi='pacman -Slq | fzf --preview "pacman -Si {}" | xargs -ro pacman -Si'

# Transmission
alias t='watch -n 0.1 transmission-remote -l'
alias tsm='transmission-remote'
# Sort list by name column excluding first and last line.
tsml() {
    transmission-remote -l \
        | awk 'NR==1{print; next;} {if(last) print last | "sort -k10"; last=$0;} END {close("sort -k10"); print last}'
}
# Fzf select torrents to remove and delete.
tsmr() {
    tsml | sed '1d;$d' | awk -F'  ' '{printf("%2s %s\n", $3, $NF)}' \
        | fzf \
        | awk '{print $1}' \
        | xargs -I {} transmission-remote -t '{}' --remove-and-delete
}

# Uncategorized
alias cal='cal -m' # Monday first day of week.
alias cdp='cd P'
alias flexget='~/data/.environments/flexget/bin/flexget'
alias i='imv'
alias j='julia'
alias ll='ls --almost-all --human-readable -l'
alias m='neomutt'
alias ms='mailsync'
alias msl='while true; do mailsync; sleep 1; done'
alias mullvad-gui='"/opt/Mullvad VPN/mullvad-gui"'
alias printpath='printf "%s\n" "$PATH" | sed "s/:/\n/g"'
alias pwdc='pwd C'
alias shck='shellcheck'
alias tree='tree -a -I .git' # ignore .git directory
alias z='zathura'
alias zzz='systemctl suspend'
