#!/bin/sh
# Aliases for often used commands.

# Suffix alias
# man zshbuiltins
alias -s git='git clone'
alias -s jpg=sxiv
alias -s lua='$EDITOR'
alias -s mkv=mpv
alias -s mp4=mpv
alias -s ods=localc
alias -s pdf='$READER'
alias -s png=sxiv
alias -s py='$EDITOR'
alias -s tex='$EDITOR'
alias -s webm=mpv
alias -s xopp=xournalpp

# Color automatically
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

# Git
alias g='git'
alias grt='cd "$(git rev-parse --show-toplevel)"'

# Go up directories
alias .1='cd ../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'

# Interactive and verbose
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'

# Neovim
alias sv='sudoedit'
alias v='$EDITOR'
alias vdf='cd "$DOTDIR" && $EDITOR'

# Often used directories
alias cadv='cd $PROGRAMMINGDIR/advent-of-code-2022'
alias cda='cd "$DATADIR"; l'
alias cdf='cd "$DOTDIR"; l'
alias cm='cd "$MASTERDIR"; l'
alias cmc='cd "$MASTERDIR/2023s"; l'
alias cpr='cd "$PROGRAMMINGDIR"; l'
alias ct='cd "$TEMPDIR"; l'
alias ctor='cd "$TORRENTDIR"; l'

# Pacman
alias aurs='paru -Slq | fzf --preview "paru -Si {}" | xargs -ro paru -S'
alias explicit-installed='pacman -Qqen | grep -vx "$(pacman -Qqg texlive-most)"'
alias pacq='pacman -Qq | fzf --preview "pacman -Qi {}" | xargs -ro pacman -Qi'
alias pacr='pacman -Qqe | fzf --preview "pacman -Qi {}" | xargs -ro sudo pacman -Rns'
alias pacs='pacman -Slq | fzf --preview "pacman -Si {}" | xargs -ro sudo pacman -S'

# Transmission
alias t='watch -n 0.1 transmission-remote -l'
alias tsm='transmission-remote'
# Sort list by name column excluding first and last line.
tsml() {
    transmission-remote -l \
        | awk 'NR==1{print; next;} {if(last) print last | "sort -k10"; last=$0;} END {close("sort -k10"); print last}'
}
# Fzf select torrents to remove and delete.
tsmr() {
    tsml | sed '1d;$d' | awk -F'  ' '{printf("%2s %s\n", $3, $NF)}' \
        | fzf \
        | awk '{print $1}' \
        | xargs -I {} transmission-remote -t '{}' --remove-and-delete
}

# Uncategorized
alias cal='cal -m'
alias cb='xclip -selection clipboard'
alias cdcb='cd "$(xclip -selection clipboard -o)"'
alias fd='fd --follow --hidden'
alias ftree='fd | tree --fromfile'
alias i='sxiv'
alias l='ls -lAh --time-style=long-iso'
alias m='neomutt'
alias mpvcb='mpv "$(xclip -selection clipboard -o)"'
alias ms='mailsync'
alias msl='while true; do mailsync; sleep 1; done'
alias n='newsboat'
alias nf='neofetch'
alias printpath='echo "$PATH" | sed "s/:/\n/g"'
alias shck='shellcheck'
alias tree='tree -a -I .git' # ignore .git directory
alias uumount='udiskie-umount'
alias wtr='curl wttr.in'
alias x='xournalpp'
alias z='zathura'
alias zzz='systemctl suspend'
