#!/bin/sh
# shellcheck source-path=SCRIPTDIR/..
# autostart
dunst &
redshift &
udiskie &
transmission-daemon &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &

# X11
xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"
xrandr --dpi 96

# keyboard settings
xset r 66 # caps lock
xset r rate 150 50
setxkbmap us -variant colemak
xmodmap -e 'keycode 66 = BackSpace Escape BackSpace BackSpace BackSpace BackSpace BackSpace'

# device specific
if [ -x "$XDG_CONFIG_HOME/x11/device_specific" ]; then
	. "$XDG_CONFIG_HOME/x11/device_specific"
fi

# start window manager
exec awesome
