#!/bin/sh

# Autostart
/etc/X11/xinit/xinitrc.d/50-systemd-user.sh &
dunst &
easyeffects --gapplication-service &
flameshot &
redshift &
transmission-daemon &
udiskie &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend' '' &

# Keyboard
xset r 66 # caps lock
xset r rate 200 50
setxkbmap us -variant colemak

# X11
xrdb -merge "$XDG_CONFIG_HOME/x11/xresources"
xrandr --dpi 96

# Device specific
case "$(hostnamectl hostname)" in
    *desktop*)
        # Autostart
        flexget daemon start -d &

        # Display
        xrandr --output DisplayPort-1 --primary --right-of DisplayPort-2
        xrandr --output DisplayPort-1 --set TearFree on
        xrandr --output DisplayPort-2 --set TearFree on

        # Mouse
        xinput set-prop 'pointer:Logitech G Pro ' 'libinput Accel Profile Enabled' 0, 1
        xinput set-prop 'pointer:Logitech G Pro ' 'libinput Accel Speed' -0.4
        ;;
    *laptop*)
        # Autostart
        blueman-applet &
        ;;
esac

# Start window manager (must be last)
exec awesome
