#!/bin/sh
# Aliases for often used commands.

# man zshbuiltins
if [ "$SHELL" = "/bin/zsh" ]; then
    alias -g C='| wl-copy'
    alias -g P='"$(wl-paste)"'
    alias -s git='git clone'
fi

# Color automatically
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias ls='ls --color=auto'

# Often used directories
alias cda='cd "$DATADIR"; l'
alias cdf='cd "$DOTDIR"; l'
alias cn='cd "$DATADIR/notes"; l'
alias cpr='cd "$PROJECTDIR"; l'
alias ct='cd "$TEMPDIR"; l'
alias ctor='cd "$TORRENTDIR"; l'
alias vdf='cd "$DOTDIR"; $EDITOR'
# university
alias cf='cd "$PROJECTDIR/Fermions.jl"; l'
alias cj='cd "$PROJECTDIR/RAS_DMFT.jl"; l'
alias cjo='cd "$PROJECTDIR/journal"; l'
alias cm='cd "$MASTERDIR"; l'
alias cmc='cd "$MASTERDIR/2025w"; l'
alias cmd='cd "$MASTERDIR/masters_thesis/data"; l'
alias cmm='cd "$MASTERDIR/masters_thesis"; l'
alias cs='cd "$PROJECTDIR/masters_scripts"; l'
alias vjo='cd "$PROJECTDIR/journal"; $EDITOR'

# ASC
alias sq='squeue -o "%.18i %.10Q %.12P %.40j %.8u %.2t %.10M %.6D %R" -u $USER'
alias sqa='squeue -o "%.18i %.10Q %.12P %.40j %.8u %.2t %.10M %.6D %R"'

# fd
alias fd='fd --follow --hidden'
alias fd1='fd --exact-depth 1'
alias ftree='fd | tree --fromfile'

# kitty
alias icat='kitty icat'
[ "$TERM" = 'xterm-kitty' ] && alias ssh='kitten ssh'

# Git
alias g='git'
alias grt='cd "$(git rev-parse --show-toplevel)"'
alias gs='' # Don't run Ghostscript by mistake.

# Go up directories
alias .1='cd ../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'

# Interactive and verbose
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'

# lsd
alias l='lsd --long --almost-all --ignore-glob ""' # don't ignore anything
alias lt1='lsd --tree --almost-all --depth 1'
alias lt2='lsd --tree --almost-all --depth 2'
alias lt3='lsd --tree --almost-all --depth 3'
alias lt='lsd --tree --almost-all'

# Neovim
alias sv='sudoedit'
alias v='$EDITOR'

# openconnect
alias vpnoff='sudo killall --quiet -SIGINT openconnect'

# Pacman
alias aurs='paru -Slq | fzf --preview "paru -Si {}" | xargs -ro paru -S'
alias aursi='paru -Slq | fzf --preview "paru -Si {}" | xargs -ro paru -Si'
alias explicit-installed='pacman -Qqe | grep -vx "$(pacman -Qqg texlive)"'
alias mirror='sudo reflector --verbose --latest 8 --sort rate --protocol https --save /etc/pacman.d/mirrorlist'
alias pacq='pacman -Qq | fzf --preview "pacman -Qi {}" | xargs -ro pacman -Qi'
alias pacr='pacman -Qqe | fzf --preview "pacman -Qi {}" | xargs -ro sudo pacman -Rns'
alias pacs='pacman -Slq | fzf --preview "pacman -Si {}" | xargs -ro sudo pacman -S'
alias pacsi='pacman -Slq | fzf --preview "pacman -Si {}" | xargs -ro pacman -Si'

# Transmission
alias t='watch -n 0.1 transmission-remote -l'
alias tsm='transmission-remote'
# Sort list by name column excluding first and last line.
tsml() {
    transmission-remote -l \
        | awk 'NR==1{print; next;} {if(last) print last | "sort -k10"; last=$0;} END {close("sort -k10"); print last}'
}
# Fzf select torrents to remove and delete.
tsmr() {
    tsml | sed '1d;$d' | awk -F'  ' '{printf("%2s %s\n", $3, $NF)}' \
        | fzf \
        | awk '{print $1}' \
        | xargs -I {} transmission-remote -t '{}' --remove-and-delete
}

# Uncategorized
alias cal='cal -m' # Monday first day of week.
alias cdp='cd P'
alias ff='firefox'
alias i='imv'
alias j='julia'
alias ll='ls --almost-all --human-readable -l'
alias m='neomutt'
alias ms='mbsync --config "$XDG_CONFIG_HOME/isync/mbsyncrc" --all'
alias mullvad-gui='"/opt/Mullvad VPN/mullvad-gui"'
alias printpath='printf "%s\n" "$PATH" | sed "s/:/\n/g"'
alias pwdc='pwd C'
alias shck='shellcheck'
alias tree='tree -a -I .git' # ignore .git directory
alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias z='zathura'

# Functions
yesterday() {
    date -d 'yesterday' --iso-8601
}

today() {
    date --iso-8601
}

tomorrow() {
    date -d 'tomorrow' --iso-8601
}
